### ISSUE TITLE
[Warning!!!] Default snowflake id in multiple node deployment may result primary key CONFLICT!!!

### ISSUE THREAD

**Issue by zhwei820** [go-gorm/sharding#65]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/4001744/186054286-e9ceb29f-954f-40d9-ad92-e258462e161f.png">

**Comment by hyperphoton** [comment]
Use custom PrimaryKeyGeneratorFn in this case.

**Comment by hyperphoton** [comment]
Added note for this case in README.

**Comment by zishiguo** [comment]
I also met it.
[Since this is essentially resetting that step value to zero every time - every ID generated in the same same millisecond will be a duplicate ID.](https://github.com/bwmarrin/snowflake/issues/9#issuecomment-408102649)

Default snowflake id use `tableIdx`,  `tableIdx` is  table suffix，such as 1,2, **, 9.  with distributed deployment,   muliple  nodes write to `users_04` in in the same millisecond, these nodes has same node id,  step value increment from zero. 

my solution as follows
```golang
	hostname, err := os.Hostname()
	if err != nil {
		return nil, fmt.Errorf("get hostname: %w", err)
	}
	snowflakeNodes := make([]*snowflake.Node, 1024)
	for i := int64(0); i < 1024; i++ {
		n, err := snowflake.NewNode(i)
		if err != nil {
			return nil, fmt.Errorf("init snowflake node error, %w", err)
		}
		snowflakeNodes[i] = n
	}
	err = db.Use(sharding.Register(sharding.Config{
		ShardingKey:         "user_id",
		NumberOfShards:      10,
		PrimaryKeyGenerator: sharding.PKSnowflake,
		PrimaryKeyGeneratorFn: func(tableIdx int64) int64 {
			hostname2 := fmt.Sprintf("%s%d", hostname, tableIdx)
			nodeID := helper.GenerateNodeID(hostname2)
			return snowflakeNodes[nodeID].Generate().Int64()
		},
	}, "xxx", "xxx")

```

**Comment by zishiguo** [comment]
@hyperphoton I can't see it now in README file

**Comment by zishiguo** [comment]
@zhwei820 Do you solve this question?

**Comment by zishiguo** [comment]
function GenerateNodeID
```golang
func GenerateNodeID(hostname string) int64 {
	// Convert the hostname to a numeric value
	hash := int64(0)
	for _, c := range hostname {
		hash = 31*hash + int64(int(c))
	}

	// Ensure the node ID is within the range of Snowflake node ID (0-1023)
	nodeID := hash % 1024
	if nodeID < 0 {
		nodeID += 1024
	}

	return nodeID
}
```
